export const LOGIN_USUARIO_REQUEST = 'LOGIN_USUARIO_REQUEST';
export const LOGIN_USUARIO_SUCCESS = 'LOGIN_USUARIO_SUCCESS';
export const LOGIN_USUARIO_FAILURE = 'LOGIN_USUARIO_FAILURE';

export const REGISTER_USUARIO_REQUEST = 'REGISTER_USUARIO_REQUEST';
export const REGISTER_USUARIO_SUCCESS = 'REGISTER_USUARIO_SUCCESS';
export const REGISTER_USUARIO_FAILURE = 'REGISTER_USUARIO_FAILURE';

export const GET_USUARIO_PERFIL_REQUEST = 'GET_USUARIO_PERFIL_REQUEST';
export const GET_USUARIO_PERFIL_SUCCESS = 'GET_USUARIO_PERFIL_SUCCESS';
export const GET_USUARIO_PERFIL_FAILURE = 'GET_USUARIO_PERFIL_FAILURE';

export const UPDATE_USUARIO_REQUEST = 'UPDATE_USUARIO_REQUEST';
export const UPDATE_USUARIO_SUCCESS = 'UPDATE_USUARIO_SUCCESS';
export const UPDATE_USUARIO_FAILURE = 'UPDATE_USUARIO_FAILURE';

export const FIND_USUARIO_BY_ID_REQUEST = 'FIND_USUARIO_BY_ID_REQUEST';
export const FIND_USUARIO_BY_ID_SUCCESS = 'FIND_USUARIO_BY_ID_SUCCESS';
export const FIND_USUARIO_BY_ID_FAILURE = 'FIND_USUARIO_BY_ID_FAILURE';

export const FOLLOW_USUARIO_REQUEST = 'FOLLOW_USUARIO_REQUEST';
export const FOLLOW_USUARIO_SUCCESS = 'FOLLOW_USUARIO_SUCCESS';
export const FOLLOW_USUARIO_FAILURE = 'FOLLOW_USUARIO_FAILURE';

export const LOGOUT = 'LOGOUT';


